@baseUrl = http://localhost:8080
### localhost request links
### Gets all contacts
GET {{baseUrl}}/users HTTP/1.1

### Gets a contact by id
GET {{baseUrl}}/users/65ac5da5048d1d549497ceeb HTTP/1.1

### Create a contact
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "firstName": "Raul",
    "lastName": "Hernandez",
    "email": "raul@hndz.com",
    "favoriteColor": "Orange",
    "birthday": "2014-09-09"
}

### Updating a contact by Id, you can send all data or just the columns to update
PUT {{baseUrl}}/users/65ac5da5048d1d549497ceeb
Content-Type: application/json

{
    "firstName": "Raulon",
    "lastName": "Hernandez",
    "email": "raul2@hndz.com",
    "favoriteColor": "Red",
    "birthday": "2014-09-09"
}

### Deleting an specific contact
DELETE {{baseUrl}}/users/65a2ff17cf7be73b1b41dbb8